# Generated by Django 4.2.7 on 2023-11-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('caracteristicas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('rol', models.CharField(choices=[('administrador', 'administrador'), ('medico veterinario', 'medico veterinario'), ('dueño de mascota', 'dueño de mascota'), ('vendedor', 'vendedor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.mascota')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.medicamento')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.persona')),
            ],
        ),
        migrations.CreateModel(
            name='MedFact',
            fields=[
                ('id_medfact', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor_vto', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='persona_cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.persona'),
        ),
        migrations.CreateModel(
            name='Hc',
            fields=[
                ('id_hc', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('sistematogia', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('procedimiento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=200)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.mascota')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVet',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.mascota')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.orden')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.persona')),
            ],
        ),
    ]
